server:
  port: 80
spring:
  application:
    name: cloud-consumer-feign-order80

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#设置feign客户端调用服务的超时时间
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
#配置feign日志级别
logging:
  level:
    com.atzy.springcloud.service.PaymentFeignService: debug
